package org.elixir_lang.beam.decompiler

import org.elixir_lang.ElixirLexer
import org.elixir_lang.beam.chunk.DebugInfo
import org.elixir_lang.beam.chunk.beam_documentation.Documentation
import org.elixir_lang.beam.chunk.debug_info.v1.elixir_erl.V1
import org.elixir_lang.beam.chunk.debug_info.v1.elixir_erl.v1.definitions.Definition
import org.elixir_lang.beam.chunk.debug_info.v1.elixir_erl.v1.definitions.definition.Clause
import org.elixir_lang.beam.chunk.debug_info.v1.erl_abstract_code.AbstractCodeCompileOptions
import org.elixir_lang.beam.chunk.debug_info.v1.erl_abstract_code.abstract_code_compiler_options.abstract_code.Function
import org.elixir_lang.psi.ElixirTypes
import org.elixir_lang.psi.call.name.Function.DEF
import org.elixir_lang.psi.call.name.Function.DEFP

/**
 * Where a definition's decompiled clauses come from. The decompiler and the stub builder both choose through
 * [clauseSource].
 */
sealed interface ClauseSource {
    /** Parameters of the first clause. */
    val parameters: List<String>
    val isAutoGeneratedName: Boolean

    class ErlangAbstractCode(val function: Function) : ClauseSource {
        override val parameters: List<String> get() = function.clauses.firstOrNull()?.parameters.orEmpty()
        override val isAutoGeneratedName: Boolean = false
    }

    class ElixirDebugInfo(val definition: Definition, private val clauses: List<Clause>) : ClauseSource {
        override val parameters: List<String> get() = clauses.first().parameters
        override val isAutoGeneratedName: Boolean get() = clauses.first().isAutoGeneratedName
    }

    class DocsSignatures(val signatures: List<String>) : ClauseSource {
        override val parameters: List<String> get() = signatureParameters(signatures.first().replace("\r", ""))

        // Elixir names a pattern argument in a docs signature after its shape (`map`, `list`, ...), so no name
        // here is known to be from source.
        override val isAutoGeneratedName: Boolean = true
    }

    class Generated(
        val decompiler: MacroNameArity,
        private val macroNameArity: org.elixir_lang.beam.MacroNameArity
    ) : ClauseSource {
        override val parameters: List<String> get() = decompiler.parameters(macroNameArity).toList()
        override val isAutoGeneratedName: Boolean get() = macroNameArity.arity > 0
    }
}

/**
 * [documentation] is only called when the debug info cannot render the definition.
 */
fun clauseSource(
    macroNameArity: org.elixir_lang.beam.MacroNameArity,
    debugInfo: DebugInfo?,
    documentation: () -> Documentation?
): ClauseSource? =
    debugInfoClauseSource(macroNameArity, debugInfo)
        ?: documentationClauseSource(macroNameArity, documentation())

private fun debugInfoClauseSource(
    macroNameArity: org.elixir_lang.beam.MacroNameArity,
    debugInfo: DebugInfo?
): ClauseSource? =
    when (debugInfo) {
        is AbstractCodeCompileOptions ->
            when (macroNameArity.macro) {
                DEF, DEFP ->
                    debugInfo.functions.byNameArity[macroNameArity.toNameArity()]
                        ?.let { ClauseSource.ErlangAbstractCode(it) }
                else -> null
            }
        is V1 ->
            debugInfo.definitions?.get(macroNameArity)?.let { definition ->
                definition.renderedClauses()?.let { ClauseSource.ElixirDebugInfo(definition, it) }
            }
        else -> null
    }

private fun documentationClauseSource(
    macroNameArity: org.elixir_lang.beam.MacroNameArity,
    documentation: Documentation?
): ClauseSource? {
    val beamLanguage = documentation?.beamLanguage ?: "elixir"
    val decompiler = decompiler(beamLanguage, macroNameArity.toNameArity()) ?: return null

    // Docs signatures read well but are not code `unquote` can use, so only the default decompiler takes them.
    val signatures = if (decompiler === Default.INSTANCE) {
        documentation?.takeIf { it.beamLanguage == "elixir" }?.docs?.signatures(macroNameArity)
    } else {
        null
    }

    return if (!signatures.isNullOrEmpty()) {
        ClauseSource.DocsSignatures(signatures)
    } else {
        ClauseSource.Generated(decompiler, macroNameArity)
    }
}

/**
 * The top-level arguments of a docs chunk signature such as `merge(map1, map2 \\ %{})`.
 */
internal fun signatureParameters(signature: String): List<String> {
    val parameters = mutableListOf<String>()
    val lexer = ElixirLexer()
    lexer.start(signature)

    var depth = 0
    var parameterStart = -1

    while (lexer.tokenType != null) {
        when (lexer.tokenType) {
            ElixirTypes.OPENING_PARENTHESIS, ElixirTypes.OPENING_BRACKET, ElixirTypes.OPENING_CURLY,
            ElixirTypes.OPENING_BIT, ElixirTypes.FN, ElixirTypes.DO -> {
                depth++

                if (depth == 1 && parameterStart == -1) {
                    parameterStart = lexer.tokenEnd
                }
            }
            ElixirTypes.CLOSING_PARENTHESIS, ElixirTypes.CLOSING_BRACKET, ElixirTypes.CLOSING_CURLY,
            ElixirTypes.CLOSING_BIT, ElixirTypes.END -> {
                depth--

                if (depth == 0) {
                    signature.substring(parameterStart, lexer.tokenStart).trim().takeIf(String::isNotEmpty)?.let {
                        parameters.add(it)
                    }

                    return parameters
                }
            }
            ElixirTypes.COMMA ->
                if (depth == 1) {
                    parameters.add(signature.substring(parameterStart, lexer.tokenStart).trim())
                    parameterStart = lexer.tokenEnd
                }
        }

        lexer.advance()
    }

    return parameters
}
