package org.elixir_lang.code_insight

import org.elixir_lang.PlatformTestCase
import org.elixir_lang.beam.psi.BeamFileImpl
import org.elixir_lang.beam.psi.impl.CallDefinitionImpl
import org.elixir_lang.beam.psi.impl.CallDefinitionStubImpl
import org.elixir_lang.beam.psi.stubs.ModuleStub
import java.io.File

class SignatureTest : PlatformTestCase() {
    fun testBeamDefinitionKeepsItsStoredParameters() {
        assertEquals(listOf("x", "q"), beamSignature(2, listOf("x", "q"), false).parameters)
    }

    /** A stub stores no parameters when rendering the definition failed or no decompiler accepts its name. */
    fun testBeamDefinitionWithoutStoredParametersGetsGeneratedNames() {
        assertEquals(listOf("p0", "p1", "p2"), beamSignature(3, emptyList(), true).parameters)
    }

    fun testBeamZeroArityHasNoParameters() {
        assertEquals(emptyList<String>(), beamSignature(0, emptyList(), false).parameters)
    }

    private fun beamSignature(arity: Int, parameters: List<String>, isAutoGeneratedName: Boolean): Signature {
        val bytes = File("testData/org/elixir_lang/code_insight/parameter_info/beam/ebin/queue.beam").readBytes()
        val module = BeamFileImpl.buildFileStub(bytes, "queue.beam")!!.childrenStubs.single() as ModuleStub<*>
        val stub = CallDefinitionStubImpl<CallDefinitionImpl<*>>(
            module, "def", "unrendered", arity, parameters, isAutoGeneratedName
        )

        return Signature.of(CallDefinitionImpl(stub))
    }
}
