package org.elixir_lang.beam.chunk.debug_info.v1.elixir_erl.v1.definitions.definition

import com.ericsson.otp.erlang.OtpErlangAtom
import com.ericsson.otp.erlang.OtpErlangList
import com.ericsson.otp.erlang.OtpErlangObject
import com.ericsson.otp.erlang.OtpErlangTuple
import org.elixir_lang.Macro
import org.elixir_lang.Macro.rewriteGuard
import org.elixir_lang.beam.chunk.Keyword
import org.elixir_lang.beam.chunk.debug_info.logger
import org.elixir_lang.beam.chunk.debug_info.v1.elixir_erl.v1.definitions.Definition
import org.elixir_lang.beam.decompiler.Options
import org.elixir_lang.beam.decompiler.decompiler
import org.elixir_lang.beam.term.inspect
import org.elixir_lang.toOtpErlangList


class Clause(
        val definition: Definition,
        metadata: OtpErlangObject,
        arguments: OtpErlangObject,
        guards: OtpErlangObject,
        val block: OtpErlangObject
) {
    val metadata: Keyword? = org.elixir_lang.beam.chunk.from(metadata)
    val arguments: OtpErlangList = arguments.toOtpErlangList()
    private val guards: OtpErlangList? = guards as? OtpErlangList
    private val argumentStrings: Array<String> by lazy { this.arguments.map { Macro.toString(it) }.toTypedArray() }
    private val macroNameArityDecompiler by lazy {
        definition.macroNameArity?.let { macroNameArity ->
            decompiler("elixir", macroNameArity.toNameArity())?.let { decompiler -> macroNameArity to decompiler }
        }
    }
    val parameters: List<String> by lazy {
        (macroNameArityDecompiler
            ?.let { (macroNameArity, decompiler) -> decompiler.signatureParameters(macroNameArity, argumentStrings) }
            ?: argumentStrings)
            .toList()
    }
    val isAutoGeneratedName: Boolean by lazy {
        this.arguments.arity() > 0 && this.arguments.all { isGeneratedVariable(it) }
    }
    val signature: String by lazy {
        val guardsString = guardsToString(this.guards)

        macroNameArityDecompiler?.let { (macroNameArity, decompiler) ->
            val decompiled = StringBuilder()
            decompiler.appendSignature(decompiled, macroNameArity, macroNameArity.name, argumentStrings)
            decompiled.append(guardsString)

            decompiled.toString()
        } ?: "${definition.name}(${argumentStrings.joinToString(", ")})${guardsString}"
    }

    fun toMacroString(options: Options): String? =
        definition.macro?.let { macro ->
            val prefix = "$macro $signature"

            if (options.decompileBodies) {
                try {
                    val blockMacroToString = Macro.toString(block)

                    if (options.truncateDecompiledBody(blockMacroToString)) {
                        "$prefix, do: ..."
                    } else {
                        "$prefix do\n${blockMacroToString.prependIndent("  ")}\nend"
                    }
                } catch (_: StackOverflowError) {
                    "$prefix, do: ..."
                }
            } else {
                "$prefix, do: ..."
            }
        }

    companion object {
        fun from(term: OtpErlangObject, definition: Definition): Clause? =
                if (term is OtpErlangTuple) {
                    from(term, definition)
                } else {
                    logger.error("""
                                 Clause is not a tuple

                                 ## clause

                                 ```elixir
                                 ${inspect(term)}
                                 ```
                                 """.trimIndent())

                    null
                }

        const val EXPECTED_ARITY = 4

        /** A variable `elixir_def` generates, such as the `x0` of a default-argument clause. */
        fun isGeneratedVariable(term: OtpErlangObject): Boolean =
                Macro.isVariable(term) &&
                        (term as OtpErlangTuple).let { variable ->
                            (variable.elementAt(2) as OtpErlangAtom).atomValue() == "elixir_def" &&
                                    (variable.elementAt(1) as? OtpErlangList)?.any { entry ->
                                        entry is OtpErlangTuple &&
                                                entry.arity() == 2 &&
                                                (entry.elementAt(0) as? OtpErlangAtom)?.atomValue() == "generated" &&
                                                (entry.elementAt(1) as? OtpErlangAtom)?.atomValue() == "true"
                                    } == true
                        }

        private fun from(tuple: OtpErlangTuple, definition: Definition): Clause? {
            val arity = tuple.arity()

            return if (arity == EXPECTED_ARITY) {
                // https://github.com/elixir-lang/elixir/blob/8c05bb078d715504a9d34343ad807275909474ed/lib/elixir/lib/exception.ex#L231
                val (metadata, arguments, guards, block) = tuple

                Clause(definition, metadata, arguments, guards, block)
            } else {
                logger.error("""
                             Clause arity (${arity}) is not $EXPECTED_ARITY

                             ## clause

                             ```elixir
                             ${inspect(tuple)}
                             ```
                             """.trimIndent())

                null
            }
        }

        private fun guardsToString(guards: OtpErlangList?): String =
                if (guards != null) {
                    when (guards.arity()) {
                        0 -> ""
                        else -> {
                            guards.joinToString(" or ", " when ", transform = { guard ->
                                Macro.toString(rewriteGuard(guard))
                            })
                        }
                    }
                } else {
                    " when ?"
                }

    }
}

private operator fun OtpErlangTuple.component1(): OtpErlangObject = this.elementAt(0)
private operator fun OtpErlangTuple.component2(): OtpErlangObject = this.elementAt(1)
private operator fun OtpErlangTuple.component3(): OtpErlangObject = this.elementAt(2)
private operator fun OtpErlangTuple.component4(): OtpErlangObject = this.elementAt(3)
