package org.elixir_lang.snapshot

/**
 * Fails when any reference in an input directory resolves differently, or any module in it defines something
 * different, from that directory's committed snapshot.
 */
class ResolutionSnapshotTest : SnapshotTestCase() {
    fun testCallableDeclaration() =
        assertSnapshot("psi/callable_declaration", "snapshot/callable_declaration.resolution.txt")

    fun testInputs() = assertSnapshot("snapshot/inputs", "snapshot/inputs.resolution.txt")

    private fun assertSnapshot(inputDirectory: String, golden: String) {
        val (root, files) = copyInputs(inputDirectory)
        assertGolden(golden, HEADER, ResolutionSnapshot(root).lines(files), REGENERATE)
    }

    companion object {
        private const val REGENERATE =
            "./gradlew test --tests org.elixir_lang.snapshot.ResolutionSnapshotTest -PoverwriteTestData=true"
        private val HEADER = listOf(
            "# Generated by ResolutionSnapshotTest: do not edit. Regenerate with $REGENERATE",
            "# One line per reference: file:line:column  system  reference class  `text`  ->  targets.",
            "# One line per module: file:line:column  module  names; then per definition clause in it:",
            "#   file:line:column  definition  module  name/arity  form  visibility presentation time,",
            "#   or, when no declaration is built from the clause, file:line:column  definition  module  " +
                "(no declaration)  `first line`.",
            "# Review each moved line in a diff.",
        )
    }
}
