# Records what the running Elixir's compiler says about the resolution snapshot's input directories: in
# `<version>/<input>.facts`, every reference it traced and what it resolved to, every alias it expanded, what each
# module defines, and the errors of files that do not compile.
#
# The facts are per Elixir version, so run this once with each Elixir CI tests, from this directory:
# `mise exec elixir@<elixir>-otp-<otp major> erlang@<otp> -- elixir generate.exs`. An argument writes the version
# directory under that directory instead.

defmodule CompilerFacts.Tracer do
  @sink {__MODULE__, :sink}
  @kinds [
    :remote_function,
    :remote_macro,
    :imported_function,
    :imported_macro,
    :imported_quoted,
    :local_function,
    :local_macro,
    :alias_reference
  ]

  def sink, do: @sink

  def trace(event, env) when is_tuple(event) and elem(event, 0) in @kinds do
    send(:persistent_term.get(@sink), {:event, env.file, env.module, env.aliases, event})
    :ok
  end

  def trace(_event, _env), do: :ok
end

defmodule CompilerFacts do
  @inputs [{"callable_declaration", "../../psi/callable_declaration"}, {"inputs", "../inputs"}]

  def run(argv) do
    root =
      case argv do
        [] -> __DIR__
        [root] -> root
      end

    directory = Path.join(root, System.version())
    File.mkdir_p!(directory)
    Code.put_compiler_option(:parser_options, columns: true)
    Code.put_compiler_option(:debug_info, true)
    Code.put_compiler_option(:tracers, [CompilerFacts.Tracer])

    for {name, input} <- @inputs do
      input = Path.expand(input, __DIR__)
      File.write!(Path.join(directory, name <> ".facts"), Enum.join([header() | facts(input)], "\n") <> "\n")
    end
  end

  defp header do
    "# Elixir #{System.version()}. Generated by generate.exs; do not edit. Regenerate in " <>
      "testData/org/elixir_lang/snapshot/compiler with " <>
      "`mise exec elixir@<elixir>-otp-<otp major> erlang@<otp> -- elixir generate.exs`."
  end

  defp facts(input) do
    files = input |> Path.join("*.ex") |> Path.wildcard() |> Enum.reject(&provided?/1)
    {events, modules, errors} = compile(files, [], [], [])
    # Left loaded, a module would make the next input directory's file that defines it look provided.
    purge(modules)
    sources = Map.new(files, &{&1, &1 |> File.read!() |> String.split("\n")})

    diagnostics =
      for {file, line, kind} <- errors do
        path = Path.relative_to(file, input)
        {path, line, 0, "diag #{path}:#{line} #{kind}"}
      end

    positioned = Enum.flat_map(events, &event_line(&1, input, sources)) ++ diagnostics

    definitions = Enum.flat_map(modules, &definition_lines/1)

    Enum.uniq(Enum.map(Enum.sort(positioned), &elem(&1, 3)) ++ Enum.map(Enum.sort(definitions), &elem(&1, 1)))
  end

  # A file whose modules the running Elixir already provides stands in for them; compiling it would replace them.
  defp provided?(file) do
    modules =
      case Code.string_to_quoted!(File.read!(file)) do
        {:__block__, _, forms} -> forms
        form -> [form]
      end
      |> Enum.flat_map(fn
        {:defmodule, _, [{:__aliases__, _, segments} | _]} -> [Module.concat(segments)]
        _ -> []
      end)

    modules != [] and Enum.all?(modules, &Code.ensure_loaded?/1)
  end

  # The compiler stops every other file at the first file that fails, so which failing file it reports is a race.
  defp compile([], events, modules, errors), do: {events, modules, errors}

  defp compile(files, events, modules, errors) do
    {result, round_events, round_modules} = compile_round(files)

    case result do
      {:ok, _, _} ->
        {events ++ round_events, modules ++ round_modules, errors}

      # The last error is the one that stopped the round. The errors before it may include some that files it then
      # stopped had already reported, so only its file's are kept.
      {:error, round_errors, _} ->
        failed = round_errors |> List.last() |> error_file()

        failed_errors =
          for error <- round_errors, error_file(error) == failed, kind = error_kind(error), kind != :logged do
            {failed, error_line(error), kind}
          end

        purge(round_modules)

        compile(
          List.delete(files, failed),
          events ++ Enum.filter(round_events, &(elem(&1, 0) == failed)),
          modules ++ Enum.filter(round_modules, &(elem(&1, 0) == failed)),
          errors ++ failed_errors
        )
    end
  end

  defp purge(modules) do
    for {_, module, _} <- modules do
      :code.purge(module)
      :code.delete(module)
    end
  end

  # On 1.14 a round started in the process of a round the compiler stopped never returns.
  defp compile_round(files) do
    parent = self()

    {pid, monitor} =
      spawn_monitor(fn ->
        caller = self()
        :persistent_term.put(CompilerFacts.Tracer.sink(), caller)
        each_module = fn file, module, binary -> send(caller, {:module, file, module, binary}) end
        result = Kernel.ParallelCompiler.compile(files, each_module: each_module, return_diagnostics: true)
        {events, modules} = drain([], [])
        send(parent, {:round, self(), result, events, modules})
      end)

    receive do
      {:round, ^pid, result, events, modules} ->
        Process.demonitor(monitor, [:flush])
        {result, events, modules}

      {:DOWN, ^monitor, :process, ^pid, reason} ->
        raise "a compilation round exited: #{inspect(reason)}"
    end
  end

  defp drain(events, modules) do
    receive do
      {:event, file, module, aliases, event} -> drain([{file, module, aliases, event} | events], modules)
      {:module, file, module, binary} -> drain(events, [{file, module, binary} | modules])
    after
      0 -> {Enum.reverse(events), Enum.reverse(modules)}
    end
  end

  # Before 1.15 an error is `{file, line, message}`; from 1.15 it is a diagnostic map.
  defp error_file({file, _line, _message}), do: Path.expand(file)
  defp error_file(%{file: file}), do: Path.expand(file)

  defp error_line({_file, line, _message}), do: line || 0
  defp error_line(%{position: {line, _column}}), do: line
  defp error_line(%{position: line}) when is_integer(line), do: line
  defp error_line(%{}), do: 0

  # The compiler's wording differs between versions; the kind it reports does not.
  defp error_kind({_file, _line, message}), do: error_kind(message)
  defp error_kind(%{message: message}), do: error_kind(message)

  defp error_kind(message) do
    cond do
      # From 1.15 a module's errors are each reported, then summarised in one more that names no position.
      message =~ "errors have been logged" -> :logged
      match = Regex.run(~r/undefined function (\S+\/\d+)/, message) -> "undefined_function " <> Enum.at(match, 1)
      match = Regex.run(~r/type (\S+\/\d+) undefined/, message) -> "undefined_type " <> Enum.at(match, 1)
      match = Regex.run(~r/module (\S+) is not loaded/, message) -> "module_not_available " <> Enum.at(match, 1)
      true -> raise "unclassified compiler error: " <> message
    end
  end

  defp event_line({file, module, aliases, event}, input, sources) do
    meta = elem(event, 1)

    with line when is_integer(line) <- meta[:line],
         column when is_integer(column) <- meta[:column],
         text when is_binary(text) <- Enum.at(Map.fetch!(sources, file), line - 1) do
      path = Path.relative_to(file, input)

      event_facts(event, module, aliases)
      |> Enum.flat_map(fn {spelling, fact} ->
        case spelled(text, column, spelling) do
          nil -> []
          column -> [{path, line, column, fact.("#{path}:#{line}:#{column}")}]
        end
      end)
    else
      _ -> []
    end
  end

  defp event_facts({:alias_reference, _, alias}, _module, aliases) do
    [{{:alias, alias, aliases}, &"alias #{&1} #{inspect(alias)}"}]
  end

  defp event_facts({:imported_quoted, _, module, name, arities}, _module, _aliases) do
    for arity <- arities, do: {{:name, name}, &"ref #{&1} imported_quoted #{mfa(module, name, arity)}"}
  end

  defp event_facts({kind, _, name, arity}, module, _aliases) when kind in [:local_function, :local_macro] do
    [{{:name, name}, &"ref #{&1} #{kind} #{mfa(module, name, arity)}"}]
  end

  defp event_facts({kind, _, module, name, arity}, _module, _aliases) do
    [{{:name, name}, &"ref #{&1} #{kind} #{mfa(module, name, arity)}"}]
  end

  defp mfa(module, name, arity), do: "#{inspect(module)}.#{name}/#{arity}"

  # The column where the source spells the event's name or alias, or nil when the event borrowed a position that does
  # not, as code a macro generates does. A remote call's column may be at its `.` and a capture's at its `&`.
  defp spelled(text, column, spelling) do
    rest = String.slice(text, column - 1, String.length(text))

    {skipped, rest} =
      case rest do
        "." <> rest ->
          {1, rest}

        "&" <> rest ->
          case Regex.run(~r/^(?:[A-Z]\w*(?:\.[A-Z]\w*)*|:\w+|__MODULE__)\./, rest) do
            [qualifier] ->
              length = String.length(qualifier)
              {1 + length, String.slice(rest, length, String.length(rest))}

            nil ->
              {1, rest}
          end

        rest ->
          {0, rest}
      end

    if spells?(rest, spelling), do: column + skipped
  end

  defp spells?(rest, {:name, name}) do
    name = Atom.to_string(name)

    String.starts_with?(rest, name) and
      (not Regex.match?(~r/^\w/, name) or not Regex.match?(~r/^[\w?!]/, String.slice(rest, String.length(name), 1)))
  end

  defp spells?(rest, {:alias, alias, aliases}) do
    case Regex.run(~r/^[A-Z]\w*(?:\.[A-Z]\w*)*/, rest) do
      [written] ->
        [first | others] = String.split(written, ".")
        first = Module.concat([first])
        Module.concat([Keyword.get(aliases, first, first) | others]) == alias

      nil ->
        false
    end
  end

  defp definition_lines({_file, module, binary}) do
    {:ok, {^module, [debug_info: {:debug_info_v1, backend, data}]}} = :beam_lib.chunks(binary, [:debug_info])
    {:ok, %{definitions: definitions}} = backend.debug_info(:elixir_v1, module, data, [])

    for {{name, arity}, kind, meta, _clauses} <- definitions do
      {{inspect(module), meta[:line], name, arity}, "def #{inspect(module)} #{kind} #{name}/#{arity} #{meta[:line]}"}
    end
  end
end

CompilerFacts.run(System.argv())
