# Generates the import oracle: for each case, the `import` lines alone in `cases/<case>.ex`, and in `<version>/` what
# they bring in from the module in `m.ex`, read from `__ENV__.functions` and `__ENV__.macros`, or the error the
# compiler gives. `<version>/exports.golden` is what the module exports, the set every case chooses from.
#
# The goldens are per Elixir version, so run this once with each Elixir CI tests, from this directory:
# `mise exec elixir@<elixir>-otp-<otp> erlang@<otp> -- elixir generate.exs`. Elixir is needed only here, never by the
# tests.

defmodule Oracle do
  @header [
    "# Generated by generate.exs beside the cases directory; do not edit.",
    "# Regenerate with `mise exec elixir@<elixir>-otp-<otp> erlang@<otp> -- elixir generate.exs` in testData/org/elixir_lang/psi/import/oracle."
  ]

  def cases do
    [
      {"none", ["import M"]},
      {"only_list", ["import M, only: [f: 1, g: 1, _hidden: 1, mac: 1, _hidden_mac: 1]"]},
      {"except_list", ["import M, except: [f: 1, mac: 1]"]},
      {"only_functions", ["import M, only: :functions"]},
      {"only_macros", ["import M, only: :macros"]},
      {"only_sigils", ["import M, only: :sigils"]},
      {"only_functions_except", ["import M, only: :functions, except: [f: 1]"]},
      {"only_macros_except", ["import M, only: :macros, except: [mac: 1]"]},
      {"only_sigils_except", ["import M, only: :sigils, except: [sigil_x: 2]"]},
      {"repeated_only", ["import M, only: [g: 1], only: [f: 1]"]},
      {"repeated_except", ["import M, except: [g: 1], except: [f: 1]"]},
      {"only_and_except", ["import M, only: [g: 1], except: [f: 1]"]},
      {"except_and_only", ["import M, except: [f: 1], only: [g: 1]"]},
      {"bracketed_only", ["import M, [only: [g: 1]]"]},
      {"only_string", ["import M, only: \"g\""]},
      {"except_string", ["import M, except: \"g\""]},
      {"except_variable", ["excluded = [g: 1]", "import M, except: excluded"]},
      {"except_empty_charlist", ["import M, except: ''"]},
      {"except_macro_call", ["import M, except: ~w()a"]},
      {"unsupported_option", ["import M, only: [g: 1], as: N"]},
      {"reimport_except", ["import M, only: [f: 1, g: 1, mac: 1]", "import M, except: [g: 1]"]},
      {"reimport_except_after_selector", ["import M, only: :functions", "import M, except: [g: 1]"]},
      {"reimport_only_functions", ["import M, only: [g: 1]", "import M, only: :functions"]},
      {"reimport_sigils_except", ["import M, only: [g: 1, sigil_x: 2]", "import M, only: :sigils, except: [f: 1]"]}
    ]
  end

  def run do
    {:ok, _} = Application.ensure_all_started(:ex_unit)
    [{module, _}] = Code.compile_file("m.ex")
    directory = System.version()
    File.mkdir_p!(directory)
    File.mkdir_p!("cases")

    write(Path.join(directory, "exports.golden"), entries(module.__info__(:functions), module.__info__(:macros)))

    for {name, lines} <- cases() do
      File.write!(Path.join("cases", name <> ".ex"), Enum.join(lines, "\n") <> "\n")
      write(Path.join(directory, name <> ".golden"), imported(module, lines))
    end
  end

  defp imported(module, lines) do
    source = Enum.join(lines ++ ["{__ENV__.functions, __ENV__.macros}"], "\n")

    # From 1.15 the compiler logs the error to stderr and raises a generic message.
    stderr =
      ExUnit.CaptureIO.capture_io(:stderr, fn ->
        result =
          try do
            {:ok, Code.eval_string(source)}
          rescue
            error in [CompileError] -> {:error, Exception.message(error)}
          end

        send(self(), {:result, result})
      end)

    receive do
      {:result, {:ok, {{functions, macros}, _}}} ->
        entries(Keyword.get(functions, module, []), Keyword.get(macros, module, []))

      {:result, {:error, message}} ->
        ["error: " <> error_kind(message <> "\n" <> stderr)]
    end
  end

  # The compiler's wording differs between versions; the kind it reports does not.
  defp error_kind(message) do
    cond do
      message =~ ":only and :except can only be given together" -> "only_and_except_given"
      message =~ "invalid :only option" -> "invalid_option only"
      message =~ "invalid :except option" -> "invalid_option except"
      message =~ "unsupported option" -> "unsupported_option"
      true -> raise "unclassified import error: " <> message
    end
  end

  defp entries(functions, macros) do
    ["functions"] ++ name_arities(functions) ++ ["macros"] ++ name_arities(macros)
  end

  defp name_arities(pairs) do
    pairs |> Enum.sort() |> Enum.map(fn {name, arity} -> "  #{name}/#{arity}" end)
  end

  defp write(path, lines), do: File.write!(path, Enum.join(@header ++ lines, "\n") <> "\n")
end

Oracle.run()
