package org.elixir_lang.beam

import com.intellij.openapi.vfs.LocalFileSystem
import com.intellij.openapi.vfs.newvfs.impl.VfsRootAccess
import com.intellij.psi.PsiCompiledFile
import com.intellij.psi.PsiManager
import com.intellij.psi.ResolveState
import com.intellij.psi.util.PsiTreeUtil
import org.elixir_lang.PlatformTestCase
import org.elixir_lang.beam.psi.impl.ModuleImpl
import org.elixir_lang.psi.CallDefinitionClause
import org.elixir_lang.psi.call.Call
import org.elixir_lang.psi.impl.call.finalArguments
import org.elixir_lang.psi.operation.Prefix
import org.elixir_lang.structure_view.element.CallDefinitionHead
import org.junit.Assert

/**
 * The stub's parameters must be the ones the decompiled mirror shows, for every definition that has a mirror in
 * both resolved SDKs.
 *
 * The comparison is against the *first* mirror clause of each name and arity: `ModuleImpl.setMirror` pairs a
 * stub with the last one, and the source path's parameter hints fall back to the first.
 *
 * Also prints how many exported definitions with parameters have names not flagged as generated; the counts are
 * in this class's `system-out` in the JUnit XML.
 */
class SdkStubSignatureTest : PlatformTestCase() {
    fun testElixirSdkStubParametersMatchMirror() {
        sweep(System.getenv("ELIXIR_LANG_ELIXIR_PATH"), "Elixir")
    }

    fun testErlangSdkStubParametersMatchMirror() {
        sweep(System.getenv("ERLANG_SDK_HOME"), "Erlang")
    }

    private fun sweep(root: String?, label: String) {
        Assert.assertNotNull("$label SDK env var not set", root)
        VfsRootAccess.allowRootAccess(testRootDisposable, root!!)

        val beams = SdkBeams.forSdk(root, label.lowercase())
        Assert.assertTrue("No .beam files found under $root/lib", beams.isNotEmpty())

        val mismatches = mutableListOf<String>()
        var compared = 0
        var exportedWithParameters = 0
        var exportedGenerated = 0
        val beamsWithExportedGenerated = mutableSetOf<String>()

        for ((beamLabel, file) in beams) {
            try {
                val virtualFile = LocalFileSystem.getInstance().findFileByIoFile(file) ?: continue
                val compiled = PsiManager.getInstance(project).findFile(virtualFile)

                if (compiled !is PsiCompiledFile) continue

                compiled.decompiledPsiFile

                val modules = PsiTreeUtil.findChildrenOfType(compiled, ModuleImpl::class.java)
                    .ifEmpty { compiled.children.filterIsInstance<ModuleImpl<*>>() }

                for (module in modules) {
                    for (callDefinition in (module as ModuleImpl<*>).callDefinitions()) {
                        val stub = callDefinition.stub
                        val name = stub.name
                        val arity = stub.callDefinitionClauseHeadArity()

                        if (stub.isExported && arity > 0) {
                            exportedWithParameters++

                            if (stub.isAutoGeneratedName) {
                                exportedGenerated++
                                beamsWithExportedGenerated += beamLabel
                            }
                        }

                        val mirror = callDefinition.mirror as? Call ?: continue
                        compared++

                        val expected = firstClauseParameters(mirror, name, arity)
                        val actual = stub.parameters()

                        if (expected != actual) {
                            mismatches += "$beamLabel: ${stub.resolvedFunctionName()} $name/$arity " +
                                "mirror=$expected stub=$actual"
                        }
                    }
                }
            } catch (t: Throwable) {
                mismatches += "$beamLabel: ${t.javaClass.simpleName}: ${t.message}"
            }
        }

        val real = exportedWithParameters - exportedGenerated
        println(
            "[stub-signature] $label: compared $compared definitions with a mirror; " +
                "$real/$exportedWithParameters exported definitions with parameters have names " +
                "not flagged as generated " +
                "(${"%.1f".format(100.0 * real / exportedWithParameters.coerceAtLeast(1))}%); " +
                "$exportedGenerated generated across ${beamsWithExportedGenerated.size} beams"
        )
        Assert.assertTrue("$label: no definition had a mirror to compare against", compared > 0)
        Assert.assertTrue(
            "${mismatches.size} $label stubs disagree with their decompiled mirror:\n" +
                mismatches.take(100).joinToString("\n") +
                (if (mismatches.size > 100) "\n… and ${mismatches.size - 100} more" else ""),
            mismatches.isEmpty()
        )
    }

    private fun firstClauseParameters(mirror: Call, name: String, arity: Int): List<String>? =
        mirror.parent.children
            .filterIsInstance<Call>()
            .firstOrNull { call ->
                CallDefinitionClause.`is`(call) &&
                    CallDefinitionClause.nameArityInterval(call, ResolveState.initial())?.let {
                        it.name == name && arity in it.arityInterval.closed()
                    } == true
            }
            ?.let { CallDefinitionClause.head(it) }
            ?.let { CallDefinitionHead.strip(it) as? Call }
            ?.let { head ->
                // `def not(value)` parses as `not` applied to the parenthesized operand `(value)`.
                head.finalArguments()?.map { argument ->
                    if (head is Prefix) CallDefinitionHead.stripAllOuterParentheses(argument).text else argument.text
                }
            }
}
