package org.elixir_lang.beam.psi.stubs;

import com.intellij.psi.stubs.StubElement;
import org.elixir_lang.beam.psi.CallDefinition;
import org.elixir_lang.psi.stub.call.Stubbic;
import org.jetbrains.annotations.NotNull;

import java.util.List;

public interface CallDefinitionStub<T extends CallDefinition> extends Stubbic, StubElement<T> {
    @NotNull
    String getName();

    int callDefinitionClauseHeadArity();

    boolean isExported();

    /**
     * The parameters of the first clause head as the decompiler renders them; empty for a definition it does not
     * decompile.
     */
    @NotNull
    List<String> parameters();

    /**
     * Whether the parameter names are not known to be the source's own.
     */
    boolean isAutoGeneratedName();
}
